const { chromium } = require('playwright');
const fs = require('fs');
(async () => {
 const browser = await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
 const page = await browser.newPage({viewport:{width:1920,height:1080}}), checks=[], errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const check=(name,ok,detail)=>{checks.push({name,passed:!!ok,detail});console.log(JSON.stringify(checks.at(-1)));};
 const ready=()=>page.waitForFunction(()=>window.lanternVale?.state.ready,null,{timeout:120000});
 const slider=async(id,v)=>page.locator('#'+id).evaluate((e,v)=>{e.value=String(v);e.dispatchEvent(new Event('input',{bubbles:true}));},v);
 await page.goto('http://127.0.0.1:4173/#debug');await ready();
 await page.evaluate(()=>document.querySelectorAll('details').forEach(e=>e.open=true));
 for(const id of ['bodies','fragments','cosmetics','rubble'])await slider(id,4);
 await slider('nukeScale',2);await page.locator('#noCooldown').check();
 await page.locator('#bodies').scrollIntoViewIfNeeded();
 await page.screenshot({path:'checks/destruction-settings/settings.png'});
 await page.waitForTimeout(300);await page.reload();await ready();
 check('Settings persist across reload',await page.evaluate(()=>['bodies','fragments','cosmetics','rubble'].every(id=>document.getElementById(id).value==='4')&&document.getElementById('nukeScale').value==='2'&&document.getElementById('noCooldown').checked));
 await page.evaluate(()=>lanternVale.reset());await page.waitForFunction(()=>lanternVale.state.active);await page.evaluate(()=>lanternVale.pause());
 check('World reset preserves experimental preferences',(await page.evaluate(()=>lanternVale.snapshot())).destruction.bodies===4);
 await page.evaluate(()=>document.querySelectorAll('details').forEach(e=>e.open=true));
 await page.locator('#defaultDestruction').click();
 check('Defaults restore all settings',await page.evaluate(()=>['bodies','fragments','cosmetics','rubble'].every(id=>document.getElementById(id).value==='1')&&!document.getElementById('noCooldown').checked));
 await page.locator('#noCooldown').check();
 await page.evaluate(async()=>{lanternVale.setPlane([1024,400,650],0,0);lanternVale.send({type:'weapon',weapon:'nuke'});lanternVale.send({type:'input',input:{x:0,y:0,throttle:0,bank:0,boost:false,fire:true}});await lanternVale.step(20);});
 check('No cooldown releases twenty nukes without a projectile gate',await page.evaluate(()=>{const s=lanternVale.state.snapshot;return s.stats.shots===20&&s.projectiles.length===20&&s.cooldowns.nuke===0}));
 await page.evaluate(()=>lanternVale.reset());await page.waitForFunction(()=>lanternVale.state.active);await page.evaluate(()=>lanternVale.pause());
 await page.evaluate(()=>document.querySelectorAll('details').forEach(e=>e.open=true));
 for(const id of ['bodies','fragments','cosmetics','rubble'])await slider(id,4);
 await slider('nukeScale',3);
 await page.evaluate(()=>{lanternVale.setQuality('1080');lanternVale.setPlane([1210,350,750],0,0);lanternVale.blast([1210,10,1070],'valley')});
 const unfinished=await page.evaluate(()=>lanternVale.save());
 check('Amplified pending blast is saved with resolved limits',unfinished.pendingJobs[0]?.profile.damageRadius===1260&&unfinished.pendingJobs[0]?.profile.bodyLimit===1024);
 await page.evaluate(()=>{lanternVale.inspect([1070,200,820],[1210,35,1070]);lanternVale.enter();lanternVale.controls({x:0,y:0,bank:0,throttle:0,boost:false,fire:false});});
 await page.waitForTimeout(1800);
 await page.screenshot({path:'checks/destruction-settings/extreme-blast.png',timeout:60000});
 let maxima={bodies:0,cosmetics:0,ruins:0,jobs:0,physicsMS:0};
 const clockStart=await page.evaluate(()=>({wall:performance.now(),sim:lanternVale.state.snapshot.time}));
 for(let i=0;i<20;i++){
  await page.waitForTimeout(1000);
  const state=await page.evaluate(()=>lanternVale.state);
  maxima.bodies=Math.max(maxima.bodies,state.snapshot.stats.bodies);maxima.cosmetics=Math.max(maxima.cosmetics,state.render.fragments);maxima.ruins=Math.max(maxima.ruins,state.snapshot.stats.ruins);maxima.jobs=Math.max(maxima.jobs,state.snapshot.stats.pendingJobs);maxima.physicsMS=Math.max(maxima.physicsMS,state.snapshot.stats.physicsMS);
 }
 const clockEnd=await page.evaluate(()=>({wall:performance.now(),sim:lanternVale.state.snapshot.time}));
 await page.evaluate(()=>lanternVale.pause());
 const perf=await page.evaluate(()=>{const a=lanternVale.samples.sort((a,b)=>a-b);return{samples:a.length,median:a[Math.floor(a.length*.5)],p95:a[Math.floor(a.length*.95)],worst:Math.max(...a)}});
 check('Extreme render/physics remain within chosen caps',maxima.bodies<=2048&&maxima.cosmetics<=16384&&maxima.jobs<=8,maxima);
 check('Extreme blast creates more than the old physical cap',maxima.bodies>256);
 await page.evaluate(()=>document.querySelector('#overlay').hidden=true);await page.screenshot({path:'checks/destruction-settings/aftermath.png'});
 await page.evaluate(()=>lanternVale.save());await page.reload();await ready();
 check('Amplified damage reloads without recovery dialog',await page.evaluate(()=>!document.getElementById('recovery').open&&lanternVale.state.snapshot.stats.removed>0&&lanternVale.state.snapshot.stats.pendingJobs===0));
 check('No page errors',errors.length===0,errors);
 check('No WebGL errors',await page.evaluate(()=>lanternVale.renderer.getContext().getError()===0));
 fs.writeFileSync('checks/destruction-settings/browser-report.json',JSON.stringify({browser:await browser.version(),checks,perf,maxima,simulationTiming:{wallSeconds:(clockEnd.wall-clockStart.wall)/1000,simulatedSeconds:clockEnd.sim-clockStart.sim}},null,2));
 await browser.close();if(checks.some(c=>!c.passed))process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
