const {chromium}=require('playwright'),fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});const checks=[],errors=[];const check=(name,passed,detail)=>{checks.push({name,passed:!!passed,detail});console.log(JSON.stringify(checks.at(-1)));};
try{const p=await b.newPage({viewport:{width:1920,height:1080}});p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:4173/#debug');await p.waitForFunction(()=>window.lanternVale?.state.ready,null,{timeout:120000});
 await p.addScriptTag({path:'checks/polish/audio-check.js'});const sound=await p.evaluate(()=>audioCheck());check('Audio voice caps, cleanup, and peak ceiling',sound.capped.ordinaryVoices===24&&sound.overlap.nukeVoices===4&&sound.after.ordinaryVoices===0&&sound.after.nukeVoices===0&&sound.peak<1,sound);
 await p.locator('#enter').click();await p.waitForTimeout(150);await p.evaluate(()=>{lanternVale.setPlane([1200,300,800],0,0);lanternVale.blast([1210,10,1070],'castle');});await p.waitForTimeout(700);await p.keyboard.press('p');await p.waitForFunction(()=>lanternVale.state.cameraMode==='photo');
 const before=await p.evaluate(()=>({time:lanternVale.state.render.effectTime,tick:lanternVale.state.snapshot.tick,p:lanternVale.state.snapshot.bodies.slice(0,5),jobs:lanternVale.state.snapshot.stats.pendingJobs}));await p.waitForTimeout(800);const after=await p.evaluate(()=>({time:lanternVale.state.render.effectTime,tick:lanternVale.state.snapshot.tick,p:lanternVale.state.snapshot.bodies.slice(0,5),jobs:lanternVale.state.snapshot.stats.pendingJobs}));check('Photo freezes an active blast and bodies',JSON.stringify(before)===JSON.stringify(after),{tick:before.tick,bodies:before.p.length});
 await p.evaluate(()=>window.dispatchEvent(new Event('blur')));check('Focus loss leaves photo in paused chase',await p.evaluate(()=>!lanternVale.state.active&&lanternVale.state.cameraMode==='chase'));
 await p.setViewportSize({width:1100,height:740});await p.waitForTimeout(200);check('Resize updates canvas',await p.evaluate(()=>lanternVale.renderer.domElement.clientWidth===1100));
 await p.evaluate(()=>{window.loss=lanternVale.loseContext();loss.loseContext();});await p.waitForTimeout(200);await p.evaluate(()=>loss.restoreContext());await p.waitForTimeout(800);check('Graphics recovery keeps interface usable',await p.evaluate(()=>!document.getElementById('enter').disabled&&lanternVale.renderer.getContext().getError()===0));
 await p.evaluate(()=>{lanternVale.enter();lanternVale.cinematic();lanternVale.setPlane([1210,-30,1070]);});await p.waitForTimeout(500);check('Crash returns cinematic camera to chase',await p.evaluate(()=>lanternVale.state.cameraMode==='chase'));
 await p.evaluate(()=>lanternVale.pause());
 for(let i=0;i<3;i++){await p.evaluate(()=>lanternVale.reset());await p.waitForFunction(()=>lanternVale.state.active);await p.evaluate(()=>lanternVale.pause());}
 check('Repeated resets restore intact world',await p.evaluate(()=>lanternVale.state.snapshot.stats.removed===0&&lanternVale.state.snapshot.stats.ruins===0));
 for(const hour of [12,18.5,0]) {await p.evaluate(h=>{lanternVale.send({type:'hour',hour:h});lanternVale.inspect([1030,150,880],[1210,30,1070]);document.querySelector('#overlay').hidden=true;document.querySelector('#perf').hidden=true;},hour);await p.waitForTimeout(300);await p.screenshot({path:`checks/polish/castle-${hour}.png`});}
 await p.evaluate(()=>{lanternVale.blast([1190,11,1070],'local');});await p.evaluate(()=>lanternVale.step(900));await p.evaluate(()=>{lanternVale.inspect([1140,70,1010],[1190,-2,1070]);lanternVale.send({type:'hour',hour:15.5});});await p.waitForTimeout(400);await p.screenshot({path:'checks/polish/crater.png'});
 check('No page or WebGL errors',errors.length===0&&await p.evaluate(()=>lanternVale.renderer.getContext().getError()===0),errors);fs.writeFileSync('checks/polish/edge-report.json',JSON.stringify({browser:await b.version(),checks},null,2));if(checks.some(c=>!c.passed))process.exitCode=1;
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
