const {chromium}=require('playwright'),fs=require('fs');const url=process.env.GAME_URL||'http://127.0.0.1:4173/';
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true}),tests=[];const check=(name,passed)=>{tests.push({name,passed:!!passed});console.log(name,passed)};
let p=await b.newPage();await p.addInitScript(()=>{const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...a){return type==='webgl2'?null:get.call(this,type,...a)}});await p.goto(url+'#debug');await p.waitForSelector('#fatal:not([hidden])');check('Missing WebGL 2 has a readable error',await p.locator('#fatalMessage').textContent());await p.close();
p=await b.newPage();await p.addInitScript(()=>{const get=WebGL2RenderingContext.prototype.getProgramParameter;WebGL2RenderingContext.prototype.getProgramParameter=function(program,name){return name===this.LINK_STATUS?false:get.call(this,program,name)}});await p.goto(url+'#debug');await p.waitForSelector('#fatal:not([hidden])');check('Shader initialization failure is presented',await p.locator('#fatalDetails').textContent());await p.close();
p=await b.newPage();await p.addInitScript(()=>{IDBFactory.prototype.open=()=>{throw new DOMException('Storage disabled','SecurityError')}});await p.goto(url+'#debug');await p.waitForFunction(()=>window.lanternVale?.state.ready);check('Unavailable storage keeps the game playable',await p.evaluate(()=>!lanternVale.state.saveEnabled));await p.close();
p=await b.newPage();await p.goto(url+'#debug');await p.waitForFunction(()=>window.lanternVale?.state.ready);await p.evaluate(async()=>{const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('lantern-vale',1);r.onsuccess=()=>resolve(r.result);r.onerror=reject});await new Promise((resolve,reject)=>{let tx=db.transaction('worlds','readwrite');tx.objectStore('worlds').put({version:999,terrain:[],removed:[],ruins:[]},'current');tx.oncomplete=resolve;tx.onerror=reject});db.close()});await p.reload();await p.waitForSelector('#recovery[open]');check('Incompatible saves require a recovery choice',await p.locator('#recovery').isVisible());await p.locator('#temporary').click();await p.waitForFunction(()=>window.lanternVale?.state.ready);check('Temporary play preserves existing saves',await p.evaluate(()=>!lanternVale.state.saveEnabled));await p.close();
p=await b.newPage();await p.addInitScript(()=>{const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args){const r=put.apply(this,args),tx=this.transaction;queueMicrotask(()=>tx.abort());return r}});await p.goto(url+'#debug');await p.waitForFunction(()=>window.lanternVale?.state.ready);await p.evaluate(()=>lanternVale.save());check('Interrupted save is reported without stopping play',await p.evaluate(()=>!lanternVale.state.saveEnabled&&lanternVale.state.ready));await p.close();
p=await b.newPage();await p.goto(url+'#debug');await p.waitForFunction(()=>window.lanternVale?.state.ready);await p.evaluate(()=>document.querySelector('#world').requestPointerLock=()=>Promise.reject(new Error('test denial')));await p.locator('#enter').click();await p.waitForTimeout(100);await p.mouse.move(600,400);await p.mouse.down();await p.mouse.move(740,400);await p.mouse.up();let yaw=await p.evaluate(()=>lanternVale.state.snapshot.plane.yaw);await p.waitForTimeout(500);check('Pointer-lock rejection allows drag steering',await p.evaluate(y=>Math.abs(lanternVale.state.snapshot.plane.yaw-y)>.03,yaw));await p.evaluate(()=>lanternVale.pause());for(const h of [0,3,6,9,12,15,18,21,23.9]){await p.evaluate(h=>lanternVale.send({type:'hour',hour:h}),h);await p.waitForTimeout(50)}check('Full day/night sweep has no GL errors',await p.evaluate(()=>lanternVale.renderer.getContext().getError()===0));await p.close();
fs.writeFileSync('checks/polish/failure-report.json',JSON.stringify({browser:await b.version(),tests},null,2));await b.close();if(tests.some(t=>!t.passed))process.exitCode=1;})().catch(e=>{console.error(e);process.exit(1)});
