const {chromium}=require('playwright'),fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});const checks=[];const check=(name,passed,detail)=>{checks.push({name,passed:!!passed,detail});console.log(JSON.stringify(checks.at(-1)));};try{
 const p=await b.newPage();const ready=()=>p.waitForFunction(()=>window.lanternVale?.state.ready,null,{timeout:180000});await p.goto('http://127.0.0.1:4173/#debug');await ready();
 await p.evaluate(async()=>{const db=await new Promise(r=>{const q=indexedDB.open('lantern-vale',1);q.onsuccess=()=>r(q.result)});await new Promise((resolve,reject)=>{const tx=db.transaction('worlds','readwrite');tx.objectStore('worlds').put({reverseX:true,reverseY:false,sensitivity:1.7,nukeYield:'local',destruction:{bodies:2,fragments:1,cosmetics:1,rubble:1,noNukeCooldown:true,nukeScale:1}},'preferences');tx.oncomplete=resolve;tx.onerror=reject;});db.close();});await p.reload();await ready();
 check('Legacy preference migration preserves controls and unrestricted fire',await p.evaluate(()=>document.getElementById('nukeYield').value==='valley'&&document.getElementById('reverseX').checked&&document.getElementById('sensitivity').value==='1.7'&&document.getElementById('noCooldown').checked));
 await p.evaluate(()=>{const select=document.getElementById('nukeYield');select.value='castle';select.dispatchEvent(new Event('change'));});await p.waitForTimeout(200);await p.reload();await ready();check('Migration is one-time',await p.locator('#nukeYield').inputValue()==='castle');
 await p.evaluate(()=>{for(let i=0;i<20;i++)lanternVale.blast([1100+(i%5)*45,11,990+Math.floor(i/5)*45],'valley');});
 const saved=await p.evaluate(async()=>{const s=await lanternVale.save();return {jobs:s.pendingJobs.length,version:s.worldVersion,revision:s.revision}});check('Twenty unfinished blasts are committed',saved.jobs===20,saved);
 const start=Date.now();await p.reload();await ready();const restored=await p.evaluate(()=>({jobs:lanternVale.state.snapshot.stats.pendingJobs,removed:lanternVale.state.snapshot.stats.removed,ready:lanternVale.state.ready,version:lanternVale.world.version}));check('Restoration finishes pending work before enabling flight',restored.jobs===0&&restored.removed>1000&&restored.ready&&restored.version===saved.version,{...restored,loadSeconds:(Date.now()-start)/1000});
 await p.locator('#enter').click();await p.waitForTimeout(150);await p.evaluate(()=>{lanternVale.cinematic();lanternVale.blast(lanternVale.world.castle,'local');});await p.waitForTimeout(100);await p.evaluate(()=>lanternVale.reset());await p.waitForFunction(()=>lanternVale.state.active);await p.evaluate(()=>lanternVale.pause());check('Reset clears transient sounds and camera mode',await p.evaluate(()=>lanternVale.state.audio.ordinaryVoices===0&&lanternVale.state.audio.nukeVoices===0&&lanternVale.state.cameraMode==='chase'));
 fs.writeFileSync('checks/polish/pending-save-report.json',JSON.stringify({checks},null,2));if(checks.some(c=>!c.passed))process.exitCode=1;
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
