const {chromium}=require('playwright');const fs=require('fs'),path=require('path'),{pathToFileURL}=require('url');
(async()=>{
 const b=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
 const p=await b.newPage({viewport:{width:1440,height:900},offline:true}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 await p.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href+'#debug');await p.locator('#enter').click();
 const bx=await p.evaluate(()=>{asciiWorld.setQuality(240);return asciiWorld.riverX(220)});
 const route=[[bx-45,202,'start path'],[bx-34,220,'bridge approach'],[bx+34,220,'bridge'],[322,222,'east path'],[350,234,'fort approach'],[350,260,'gate'],[350,280,'courtyard'],[350,234,'fort exit'],[350,238,'ridge turn'],[398,232,'fort perimeter'],[413,270,'east hillside'],[418,329,'ridge climb'],[390,392,'upper ridge'],[365,425,'ridge viewpoint'],[390,392,'ridge return'],[418,329,'ridge descent'],[413,270,'east hillside return'],[398,232,'fort perimeter return'],[350,238,'fort return'],[350,234,'path junction'],[322,222,'east path return'],[bx+34,220,'east bridge'],[bx-34,220,'west bridge'],[bx-42,220,'forest turn'],[185,251,'forest entry'],[170,298,'forest'],[194,338,'forest clearing'],[238,343,'woodland endpoint'],[194,338,'woodland return'],[170,298,'forest return'],[185,251,'forest exit'],[bx-42,220,'west reach'],[220,185,'river approach'],[310,185,'swim crossing'],[310,205,'riverbank'],[322,222,'east meadow'],[350,234,'fort approach again'],[350,260,'night gate'],[350,280,'night courtyard'],[350,234,'night fort exit'],[322,222,'night path'],[bx+34,220,'night bridge approach'],[bx-34,220,'night bridge'],[bx-45,202,'home path'],[210,166,'home']];
 const preflight=await p.evaluate(route=>{const w=asciiWorld,result=[];w.reset();for(const [x,z,name] of route){let reached=false,still=0;for(let i=0;i<18000;i++){const a=w.state.player,dist=Math.hypot(a.x-x,a.z-z);if(dist<.7){reached=true;break}w.turn(Math.atan2(x-a.x,z-a.z));w.setKeys(['KeyW']);w.simulate(1/120);const b=w.state.player;if(Math.hypot(a.x-b.x,a.z-b.z)<.00001)still++;else still=0;if(still>240)break;}result.push({name,reached,player:w.state.player});if(!reached)break;}w.reset();w.setKeys([]);return result},route);console.log('PREFLIGHT',JSON.stringify(preflight.map(x=>({name:x.name,reached:x.reached}))));if(preflight.some(x=>!x.reached))throw Error('Route preflight blocked '+JSON.stringify(preflight.at(-1)));
 const start=Date.now(),log=[],milestones=[];let idx=0,previous=null,stuckSince=0,travel=0,swam=false;let nextLog=0;
 while(Date.now()-start<600000){
  const t=route[idx%route.length];
  const state=await p.evaluate(([x,z])=>{const w=asciiWorld,s=w.state.player;const distance=Math.hypot(x-s.x,z-s.z);w.turn(Math.atan2(x-s.x,z-s.z),-.025);w.setKeys(distance<1?[]:['KeyW']);return {...w.state,distance}},t);
  if(!state.active)throw Error('Exploration unexpectedly paused');
  if(previous){let moved=Math.hypot(state.player.x-previous.x,state.player.z-previous.z);travel+=moved;if(moved<.012&&state.distance>1.1){if(!stuckSince)stuckSince=Date.now()}else stuckSince=0;}
  swam ||= state.player.swimming;previous=state.player;
  if(stuckSince&&Date.now()-stuckSince>5000){log.push({error:'Movement blocked',target:t,state});throw Error('Movement blocked at '+JSON.stringify({target:t,player:state.player}));}
  if(state.distance<1){milestones.push({name:t[2],elapsed:(Date.now()-start)/1000});idx++;}
  if(Date.now()-start>nextLog){let row={seconds:Math.round((Date.now()-start)/1000),target:t[2],fps:1000/state.avgMS,hour:state.hour,player:state.player};log.push(row);console.log(JSON.stringify(row));nextLog+=30000;fs.writeFileSync(path.join(__dirname,'exploration-progress.json'),JSON.stringify({log,milestones,travel,swam},null,2));}
  await p.waitForTimeout(100);
 }
 const samples=await p.evaluate(()=>asciiWorld.samples);samples.sort((a,b)=>a-b);let report={durationSeconds:(Date.now()-start)/1000,travelMeters:travel,swam,milestones,log,errors,medianFrameMS:samples[Math.floor(samples.length*.5)],p95FrameMS:samples[Math.floor(samples.length*.95)],passed:errors.length===0&&swam&&milestones.some(m=>m.name==='ridge viewpoint')&&milestones.some(m=>m.name==='forest')};
 fs.writeFileSync(path.join(__dirname,'exploration-report.json'),JSON.stringify(report,null,2));await p.screenshot({path:path.join(__dirname,'exploration-end.png')});await b.close();console.log('COMPLETE',JSON.stringify(report));if(!report.passed)process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
