const {chromium}=require('playwright');const fs=require('fs'),path=require('path'),os=require('os'),{pathToFileURL}=require('url');
(async()=>{
 const b=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
 const folder=fs.mkdtempSync(path.join(os.tmpdir(),'Lantern Vale Offline ')),file=path.join(folder,'index.html');fs.copyFileSync(path.resolve(__dirname,'../index.html'),file);const url=pathToFileURL(file).href+'#debug';
 const page=await b.newPage({viewport:{width:1440,height:900},offline:true}),out=[],errors=[];page.on('pageerror',e=>errors.push(e.message));const check=(name,passed,detail)=>out.push({name,passed:!!passed,detail});
 await page.goto(url);check('Offline local path containing spaces loads',await page.locator('#enter').isEnabled());
 await page.evaluate(()=>document.querySelector('#world').requestPointerLock=()=>Promise.reject(new Error('Test denial')));await page.locator('#enter').click();await page.waitForTimeout(100);check('Pointer lock rejection keeps drag-to-look available',await page.evaluate(()=>lanternVale.state.active&&document.querySelector('#hint').textContent.includes('Hold and drag')));
 const yaw=await page.evaluate(()=>lanternVale.state.player.yaw);await page.mouse.move(700,450);await page.mouse.down();await page.mouse.move(780,450);await page.mouse.up();check('Drag-to-look changes yaw',Math.abs(await page.evaluate(()=>lanternVale.state.player.yaw)-yaw)>.1);
 await page.keyboard.down('w');await page.waitForTimeout(150);await page.evaluate(()=>window.dispatchEvent(new Event('blur')));let before=await page.evaluate(()=>lanternVale.state.player);await page.evaluate(()=>{for(let i=0;i<120;i++)lanternVale.simulate(1/120)});let after=await page.evaluate(()=>lanternVale.state.player);check('Focus loss pauses and clears held movement',await page.locator('#overlay').isVisible()&&Math.hypot(before.x-after.x,before.z-after.z)<.001);await page.keyboard.up('w');
 await page.locator('#settingsDetails summary').click();await page.locator('#time').fill('22');check('Time slider updates the renderer state',await page.evaluate(()=>lanternVale.state.hour===22));await page.locator('#holdTime').check();await page.locator('#enter').click();await page.waitForTimeout(500);check('Hold-time keeps time fixed while playing',await page.evaluate(()=>lanternVale.state.hour===22));
 let position=await page.evaluate(()=>{window.testExt=lanternVale.loseContext();let p=lanternVale.state.player;testExt.loseContext();return p});await page.waitForFunction(()=>!lanternVale.state.resourcesValid);check('Context loss pauses and disables entry',await page.locator('#enter').isDisabled()&&await page.locator('#overlay').isVisible());await page.evaluate(()=>testExt.restoreContext());await page.waitForFunction(()=>lanternVale.state.resourcesValid,{},{timeout:20000});check('Context restoration preserves position and rebuilds resources',await page.evaluate(p=>Math.hypot(lanternVale.state.player.x-p.x,lanternVale.state.player.z-p.z)<.001&&lanternVale.getError()===0,position));
 await page.evaluate(()=>{lanternVale.setView(350,275,0,-1.2);lanternVale.setHour(12);lanternVale.render()});let a=await page.evaluate(()=>lanternVale.readCell(Math.floor(lanternVale.state.columns/2),Math.floor(lanternVale.state.rows/2)));await page.waitForTimeout(200);let c=await page.evaluate(()=>lanternVale.readCell(Math.floor(lanternVale.state.columns/2),Math.floor(lanternVale.state.rows/2)));check('Paused stationary scene remains stable',JSON.stringify(a)===JSON.stringify(c));
 const hits=await page.evaluate(()=>{const w=lanternVale;w.setDiagnostic(1);w.setView(350,280,0,.05);let wall=w.readCell(Math.floor(w.state.columns/2),Math.floor(w.state.rows/2));w.setView(w.riverX(180),180,0,-1.4,4);let water=w.readCell(Math.floor(w.state.columns/2),Math.floor(w.state.rows/2));w.setDiagnostic(0);return {wall,water}});function materialRGB(m){return [.37,.63,.19].map(v=>Math.round(Math.pow((m*v)%1,.85)*255))}check('Nearest-hit selection sees wall before distant scenery',hits.wall.slice(0,3).every((v,i)=>Math.abs(v-materialRGB(6)[i])<=2),hits.wall);check('Water surface wins over submerged terrain',hits.water.slice(0,3).every((v,i)=>Math.abs(v-materialRGB(8)[i])<=2),hits.water);
 const cycle=[];for(const hour of [0,3,6,9,12,15,18,21,23.9]){await page.evaluate(h=>{lanternVale.setView(350,237,0,.15);lanternVale.setHour(h)},hour);cycle.push({hour,error:await page.evaluate(()=>lanternVale.getError())})}check('Full day/night sweep renders without GL errors',cycle.every(x=>x.error===0));
 const disabled=await b.newPage();await disabled.addInitScript(()=>{let original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(kind,...rest){if(kind==='webgl2')return null;return original.call(this,kind,...rest)}});await disabled.goto(url);check('Missing WebGL 2 shows an actionable error',await disabled.locator('#fatal').isVisible()&&(await disabled.locator('#fatalText').textContent()).includes('WebGL 2'));
 const failed=await b.newPage();await failed.addInitScript(()=>{WebGL2RenderingContext.prototype.getShaderParameter=()=>false;WebGL2RenderingContext.prototype.getShaderInfoLog=()=> 'Injected shader failure'});await failed.goto(url);check('Shader failure is presented instead of a blank screen',await failed.locator('#fatal').isVisible()&&(await failed.locator('#fatalDetail').textContent()).includes('Injected shader failure'));
 check('No unexpected JavaScript errors',errors.length===0,errors);fs.writeFileSync(path.join(__dirname,'recovery-report.json'),JSON.stringify({tests:out},null,2));console.log(JSON.stringify(out,null,2));await b.close();fs.rmSync(folder,{recursive:true,force:true});if(out.some(x=>!x.passed))process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
